package com.oyvindnordhagen.dummy {

	public class DummyStrings {
		public static const LIPSUM : String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consectetur convallis odio. Sed a ligula. Nullam vel nulla in magna pulvinar semper. Praesent venenatis blandit ligula. Duis sagittis consequat enim. Vivamus eget lectus. Pellentesque vulputate, lectus sit amet fermentum porttitor, est elit tincidunt purus, faucibus tincidunt quam ipsum vel purus. Sed est sem, hendrerit non, scelerisque eget, imperdiet vitae, tellus. Phasellus tortor purus, luctus non, vulputate porttitor, tempor varius, tellus. Ut justo felis, mollis congue, gravida non, semper id, nibh. Aenean eu sapien. Aliquam a lorem vitae dui fermentum mattis. Morbi laoreet diam id nisl. Ut vel nulla. Sed at eros id nibh sodales lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae";
		public static const LIPSUM_SPACES_ONLY : String = "Lorem Ipsum Dolor Sit Amet Consectetur Adipiscing Elit Nam Consectetur Convallis Odio Sed a Ligula Nullam Vel Nulla in Magna Pulvinar Semper Praesent Venenatis Blandit Ligula Duis Sagittis Consequat Enim Vivamus Eget Lectus Pellentesque Vulputate Lectus Sit Amet Fermentum Porttitor Est Elit Tincidunt Purus Faucibus Tincidunt Quam Ipsum Vel Purus Sed Est Sem Hendrerit Non Scelerisque Eget Imperdiet Vitae Tellus Phasellus Tortor Purus Luctus Non Vulputate Porttitor Tempor Varius Tellus Ut Justo Felis Mollis Congue Gravida Non Semper Id Nibh Aenean Eu Sapien Aliquam a Lorem Vitae Dui Fermentum Mattis Morbi Laoreet Diam Id Nisl Ut Vel Nulla Sed at Eros Id Nibh Sodales Lacinia Vestibulum Ante Ipsum Primis in Faucibus Orci Luctus Et Ultrices Posuere Cubilia Curae";
		public static const LIPSUM_5W : String = "Lorem ipsum dolor sit amet";
		public static const LIPSUM_SHORT : String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consectetur convallis odio. Sed a ligula. Nullam vel nulla in magna pulvinar semper. Praesent venenatis blandit ligula. Duis sagittis consequat enim. Vivamus eget lectus. Pellentesque vulputate, lectus sit amet fermentum porttitor, est elit tincidunt purus, faucibus tincidunt quam ipsum";
		public static const LIPSUM_2P : String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consectetur convallis odio. Sed a ligula. Nullam vel nulla in magna pulvinar semper. Praesent venenatis blandit ligula. Duis sagittis consequat enim. Vivamus eget lectus. Pellentesque vulputate, lectus sit amet fermentum porttitor, est elit tincidunt purus, faucibus tincidunt quam ipsum vel purus. Sed est sem, hendrerit non, scelerisque eget, imperdiet vitae, tellus. Phasellus tortor purus, luctus non, vulputate porttitor, tempor varius, tellus. Ut justo felis, mollis congue, gravida non, semper id, nibh. Aenean eu sapien. Aliquam a lorem vitae dui fermentum mattis. Morbi laoreet diam id nisl. Ut vel nulla. Sed at eros id nibh sodales lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consectetur convallis odio. Sed a ligula. Nullam vel nulla in magna pulvinar semper. Praesent venenatis blandit ligula. Duis sagittis consequat enim. Vivamus eget lectus. Pellentesque vulputate, lectus sit amet fermentum porttitor, est elit tincidunt purus, faucibus tincidunt quam ipsum vel purus. Sed est sem, hendrerit non, scelerisque eget, imperdiet vitae, tellus. Phasellus tortor purus, luctus non, vulputate porttitor, tempor varius, tellus. Ut justo felis, mollis congue, gravida non, semper id, nibh. Aenean eu sapien. Aliquam a lorem vitae dui fermentum mattis. Morbi laoreet diam id nisl. Ut vel nulla. Sed at eros id nibh sodales lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae";
		public static const LIPSUM_2P_HTML : String = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consectetur convallis odio. Sed a ligula. Nullam vel nulla in magna pulvinar semper. Praesent venenatis blandit ligula. Duis sagittis consequat enim. Vivamus eget lectus. Pellentesque vulputate, lectus sit amet fermentum porttitor, est elit tincidunt purus, faucibus tincidunt quam ipsum vel purus. Sed est sem, hendrerit non, scelerisque eget, imperdiet vitae, tellus. Phasellus tortor purus, luctus non, vulputate porttitor, tempor varius, tellus. Ut justo felis, mollis congue, gravida non, semper id, nibh. Aenean eu sapien. Aliquam a lorem vitae dui fermentum mattis. Morbi laoreet diam id nisl. Ut vel nulla. Sed at eros id nibh sodales lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consectetur convallis odio. Sed a ligula. Nullam vel nulla in magna pulvinar semper. Praesent venenatis blandit ligula. Duis sagittis consequat enim. Vivamus eget lectus. Pellentesque vulputate, lectus sit amet fermentum porttitor, est elit tincidunt purus, faucibus tincidunt quam ipsum vel purus. Sed est sem, hendrerit non, scelerisque eget, imperdiet vitae, tellus. Phasellus tortor purus, luctus non, vulputate porttitor, tempor varius, tellus. Ut justo felis, mollis congue, gravida non, semper id, nibh. Aenean eu sapien. Aliquam a lorem vitae dui fermentum mattis. Morbi laoreet diam id nisl. Ut vel nulla. Sed at eros id nibh sodales lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae</p>";
		public static const LIPSUM_ARRAY : Array = LIPSUM_SPACES_ONLY.split(" ");

		private static var curLipsumWord : uint = 0;

		public static function getLipsumWord() : String {
			curLipsumWord = (curLipsumWord < LIPSUM_ARRAY.length - 1) ? curLipsumWord + 1 : 0;
			return LIPSUM_ARRAY[curLipsumWord];
		}
	}
}